
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

discovery:

homeassistant:
  customize: !include customize.yaml
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: metric
  time_zone: !secret home_time_zone
  name: !secret home_name

frontend:
  themes: !include_dir_merge_named themes

# access externally via the internet
http:
  base_url: !secret base_url
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

# mobile apps
mobile_app:

# tplink smart plugs
tplink:

# spotify
spotify:
  client_id: !secret spotify_client_id
  client_secret: !secret spotify_client_secret

# google assistant
google_assistant:
  project_id: !secret google_assistant_project_id
  service_account: !include service-account.json
  report_state: true

# Text to speech (google translate)
tts:
  - platform: google_translate

# network speeds
speedtestdotnet:

# weather
weather:
  - platform: darksky
    api_key: !secret dark_sky_api

# nzbget
nzbget:
  host: !secret nzbget_host
  port: !secret nzbget_port

# proxmox-ve
proxmoxve:
  - host: !secret proxmox_ip
    username: !secret proxmox_user
    password: !secret proxmox_pass
    verify_ssl: false
    nodes:
      - node: !secret proxmox_node
        vms:
          - !secret proxmox_vm_two
          - !secret proxmox_vm_three

group: !include groups.yaml
automation: !include_dir_merge_list automations/
script: !include scripts.yaml
sensor: !include_dir_merge_list sensors/
zone: !include zones.yaml
input_boolean: !include_dir_merge_named input-booleans/
input_select: !include_dir_merge_named input-select/
device_tracker: !include_dir_merge_list trackers/
notify: !include notify.yaml
