# determines the next bin collection date and which bins to be emptied
- platform: command_line
  name: Next Bin Collection Date
  scan_interval: 3600
  command: "python3 /config/scripts/bin-day/collection_date.py"

- platform: command_line
  name: Next Bin Collection Type
  scan_interval: 3600
  command: "python3 /config/scripts/bin-day/collection_type.py"