- platform: waze_travel_time
  origin: !secret home
  destination: !secret airport
  region: AU
  name: Airport

- platform: waze_travel_time
  origin: !secret home
  destination: !secret the_royal
  region: AU
  name: The Royal