# notification for motion while we are away from home
- alias: 'Security Alert'
  trigger:
    platform: state 
    entity_id:
      - binary_sensor.front_door_motion_sensor_motion
      - binary_sensor.kitchen_motion_sensor_motion
      - binary_sensor.office_motion_sensor
    to: 'on'
  condition:
    condition: and
    conditions:
      - condition: template
        value_template: "{{ not is_state('person.tim', 'home') }}"
      - condition: template
        value_template: "{{ not is_state('person.tracey', 'home') }}"
  action:
    - delay: '00:01:00'
    - service: notify.clicksend
      data:
        message: 'Motion detected while nobody is home'