# restart home assistant
- alias: Restart Home Assistant
  trigger:
  - entity_id: input_boolean.restart_ha
    platform: state
    to: 'on'
  action:
  - delay: '00:00:01'
  - service: input_boolean.turn_off
    data:
      entity_id: input_boolean.restart_ha
  - delay: '00:00:03'
  - service: homeassistant.restart