# set blue_night theme at start up
# can change 'default' name to any other theme
- alias: 'Set theme at startup'
  trigger:
    platform: homeassistant
    event: start
  action:
    service: frontend.set_theme
    data:
      name: blue_night